### PR TITLE
Issue: Cannot compile

### PR DESCRIPTION
**Pull request by dkudriavtsev**

### CODE REVIEW

**Comment by dkudriavtsev** [comment]
https://paste.ubuntu.com/25194964/

**Comment by sebastiencs** [comment]
Hi @dkudriavtsev, I have updated the readme.  
gcc fails to compile `ls-icons`, please read the news [instructions](https://github.com/sebastiencs/ls-icons#installation) to compile with clang

**Comment by dkudriavtsev** [comment]
Thanks!

You should also consider enabling issues, so people don't have to use dummy pull requests like I did

**Comment by sebastiencs** [comment]
@dkudriavtsev Yes I did it. Thanks !

**Comment by dkudriavtsev** [comment]
The program works, thanks for the help

**Pull request closed without merging**
